### PR TITLE
Add translations_zh_cn.json

### PR DESCRIPTION
**Pull request by yinx2002**

### CODE REVIEW

**Comment by yinx2002** [comment]
Add Chinese language

**Comment by yinx2002** [comment]
Add a modname entry in translation.py and add default value in translations_en.json

**Comment by Pruszko** [comment]
I'll change target branch to `2.6.0` (I do it like that before merging to `master`). Also:
* other user made `ru` translations as well; I'll add it alongside with your translations
* I'll add #8 together as well

**Comment by Fierioziy** [comment]
Could you also provide Chinese translations for those keys?
* `simpleServerReticlePart.drawCenterDot.header`
* `simpleServerReticlePart.drawCenterDot.body`

Those changes are probably the last ones needed before testing and releasing

**Comment by Pruszko** [comment]
Could you also provide Chinese translations for those keys?
* `simpleServerReticlePart.drawCenterDot.header`
* `simpleServerReticlePart.drawCenterDot.body`

Those changes are probably the last ones needed before testing and releasing

**Comment by yinx2002** [comment]
pull request sent in github, please check




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pruszko/DispersionReticle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 凌晨2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pruszko/DispersionReticle] Add translations_zh_cn.json (PR #9)





 
Could you also provide Chinese translations for those keys?
  
simpleServerReticlePart.drawCenterDot.header
 
simpleServerReticlePart.drawCenterDot.body
  
Those changes are probably the last ones needed before testing and releasing

**Pull request merged**
